ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
    user_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO user_count
    FROM dba_users
    WHERE username = 'TECHMIND_APP';

    IF user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER TECHMIND_APP IDENTIFIED BY "TechmindApp123"';
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER TECHMIND_APP IDENTIFIED BY "TechmindApp123" ACCOUNT UNLOCK';
    END IF;
END;
/

GRANT CREATE SESSION TO TECHMIND_APP;
GRANT CREATE TABLE TO TECHMIND_APP;
GRANT CREATE SEQUENCE TO TECHMIND_APP;
GRANT CREATE VIEW TO TECHMIND_APP;
GRANT CREATE PROCEDURE TO TECHMIND_APP;

ALTER USER TECHMIND_APP QUOTA UNLIMITED ON USERS;