CREATE TABLE users
(
    id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    name     VARCHAR2(100)                               NOT NULL,
    email    VARCHAR2(100)                               NOT NULL,
    password VARCHAR2(255)                               NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);