CREATE TABLE content
(
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    title           VARCHAR2(200)                                                             NOT NULL,
    text            CLOB                                                                      NOT NULL,
    category        VARCHAR2(50)                                                              NOT NULL,
    probability     NUMBER(4, 3)                                                              NOT NULL,
    date_processing TIMESTAMP                                                                 NOT NULL,

    CONSTRAINT pk_content PRIMARY KEY (id)
);

CREATE TABLE tag
(
    id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    name VARCHAR2(100)                                                             NOT NULL,

    CONSTRAINT pk_tag PRIMARY KEY (id),
    CONSTRAINT uk_tag_name UNIQUE (name)
);

CREATE TABLE content_tag
(
    content_id NUMBER(19) NOT NULL,
    tag_id     NUMBER(19) NOT NULL,

    CONSTRAINT pk_content_tag PRIMARY KEY (content_id, tag_id),

    CONSTRAINT fk_content_tag_content
        FOREIGN KEY (content_id) REFERENCES content (id) ON DELETE CASCADE,

    CONSTRAINT fk_content_tag_tag
        FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);