CREATE TABLE history
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id NUMBER(19) NOT NULL,
    content_id NUMBER(19) NOT NULL,
    accessed_at TIMESTAMP NOT NULL,

    CONSTRAINT pk_history PRIMARY KEY (id),
    CONSTRAINT fk_history_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT fk_history_content
        FOREIGN KEY (content_id) REFERENCES content (id) ON DELETE CASCADE
)