spring.application.name=backend

spring.profiles.default=local

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=gemini-2.5-flash-lite