spring.application.name=backend

spring.profiles.default=local

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true

content.trust.low-threshold=0.6